POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json

{
    "title": "O titulo",
    "author": "Eduardo Almeida",
    "url": "http://coiso.com",
    "likes": 0
}

###

DELETE http://localhost:3001/api/blogs/6311ef28ba660a3fc02bc8f6 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3001/api/blogs/6311ef28ba660a3fc02bc8f6 HTTP/1.1
Content-Type: application/json

{"title": "Whatever","author": "Eduardo", "url":"http://updatedCoiso.com","likes":4}